[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/ig-redirect"
  to = "https://www.instagram.com/"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200